-- 2023年8月の売上データ
INSERT INTO JOURNAL_HEADERS (ENTRY_DATE, DESCRIPTION) VALUES ('2023-08-31', '2023年8月売上');
SET @last_header_id = LAST_INSERT_ID();
INSERT INTO JOURNAL_ENTRIES (HEADER_ID, ACCOUNT_ID, TYPE, AMOUNT) VALUES (@last_header_id, 8, '借方', 580000);
INSERT INTO JOURNAL_ENTRIES (HEADER_ID, ACCOUNT_ID, TYPE, AMOUNT) VALUES (@last_header_id, 1, '貸方', 580000);

-- 2023年9月の売上データ
INSERT INTO JOURNAL_HEADERS (ENTRY_DATE, DESCRIPTION) VALUES ('2023-09-30', '2023年9月売上');
SET @last_header_id = LAST_INSERT_ID();
INSERT INTO JOURNAL_ENTRIES (HEADER_ID, ACCOUNT_ID, TYPE, AMOUNT) VALUES (@last_header_id, 8, '借方', 610000);
INSERT INTO JOURNAL_ENTRIES (HEADER_ID, ACCOUNT_ID, TYPE, AMOUNT) VALUES (@last_header_id, 1, '貸方', 610000);

-- 2023年10月の売上データ
INSERT INTO JOURNAL_HEADERS (ENTRY_DATE, DESCRIPTION) VALUES ('2023-10-31', '2023年10月売上');
SET @last_header_id = LAST_INSERT_ID();
INSERT INTO JOURNAL_ENTRIES (HEADER_ID, ACCOUNT_ID, TYPE, AMOUNT) VALUES (@last_header_id, 8, '借方', 640000);
INSERT INTO JOURNAL_ENTRIES (HEADER_ID, ACCOUNT_ID, TYPE, AMOUNT) VALUES (@last_header_id, 1, '貸方', 640000);

-- 2023年11月の売上データ
INSERT INTO JOURNAL_HEADERS (ENTRY_DATE, DESCRIPTION) VALUES ('2023-11-30', '2023年11月売上');
SET @last_header_id = LAST_INSERT_ID();
INSERT INTO JOURNAL_ENTRIES (HEADER_ID, ACCOUNT_ID, TYPE, AMOUNT) VALUES (@last_header_id, 8, '借方', 680000);
INSERT INTO JOURNAL_ENTRIES (HEADER_ID, ACCOUNT_ID, TYPE, AMOUNT) VALUES (@last_header_id, 1, '貸方', 680000);

-- 2023年12月の売上データ
INSERT INTO JOURNAL_HEADERS (ENTRY_DATE, DESCRIPTION) VALUES ('2023-12-31', '2023年12月売上');
SET @last_header_id = LAST_INSERT_ID();
INSERT INTO JOURNAL_ENTRIES (HEADER_ID, ACCOUNT_ID, TYPE, AMOUNT) VALUES (@last_header_id, 8, '借方', 750000);
INSERT INTO JOURNAL_ENTRIES (HEADER_ID, ACCOUNT_ID, TYPE, AMOUNT) VALUES (@last_header_id, 1, '貸方', 750000);

-- 2024年1月の売上データ（修正版：借方=現金(1)、貸方=売上(8)）
INSERT INTO JOURNAL_HEADERS (ENTRY_DATE, DESCRIPTION) VALUES ('2024-01-31', '2024年1月売上');
SET @last_header_id = LAST_INSERT_ID();
INSERT INTO JOURNAL_ENTRIES (HEADER_ID, ACCOUNT_ID, TYPE, AMOUNT) VALUES (@last_header_id, 1, '借方', 720000);
INSERT INTO JOURNAL_ENTRIES (HEADER_ID, ACCOUNT_ID, TYPE, AMOUNT) VALUES (@last_header_id, 8, '貸方', 720000);

-- 2024年2月の売上データ
INSERT INTO JOURNAL_HEADERS (ENTRY_DATE, DESCRIPTION) VALUES ('2024-02-29', '2024年2月売上');
SET @last_header_id = LAST_INSERT_ID();
INSERT INTO JOURNAL_ENTRIES (HEADER_ID, ACCOUNT_ID, TYPE, AMOUNT) VALUES (@last_header_id, 1, '借方', 650000);
INSERT INTO JOURNAL_ENTRIES (HEADER_ID, ACCOUNT_ID, TYPE, AMOUNT) VALUES (@last_header_id, 8, '貸方', 650000);

-- 2024年3月の売上データ
INSERT INTO JOURNAL_HEADERS (ENTRY_DATE, DESCRIPTION) VALUES ('2024-03-31', '2024年3月売上');
SET @last_header_id = LAST_INSERT_ID();
INSERT INTO JOURNAL_ENTRIES (HEADER_ID, ACCOUNT_ID, TYPE, AMOUNT) VALUES (@last_header_id, 1, '借方', 950000);
INSERT INTO JOURNAL_ENTRIES (HEADER_ID, ACCOUNT_ID, TYPE, AMOUNT) VALUES (@last_header_id, 8, '貸方', 950000);

-- 2024年4月の売上データ
INSERT INTO JOURNAL_HEADERS (ENTRY_DATE, DESCRIPTION) VALUES ('2024-04-30', '2024年4月売上');
SET @last_header_id = LAST_INSERT_ID();
INSERT INTO JOURNAL_ENTRIES (HEADER_ID, ACCOUNT_ID, TYPE, AMOUNT) VALUES (@last_header_id, 1, '借方', 780000);
INSERT INTO JOURNAL_ENTRIES (HEADER_ID, ACCOUNT_ID, TYPE, AMOUNT) VALUES (@last_header_id, 8, '貸方', 780000);

-- 2024年5月の売上データ
INSERT INTO JOURNAL_HEADERS (ENTRY_DATE, DESCRIPTION) VALUES ('2024-05-31', '2024年5月売上');
SET @last_header_id = LAST_INSERT_ID();
INSERT INTO JOURNAL_ENTRIES (HEADER_ID, ACCOUNT_ID, TYPE, AMOUNT) VALUES (@last_header_id, 1, '借方', 820000);
INSERT INTO JOURNAL_ENTRIES (HEADER_ID, ACCOUNT_ID, TYPE, AMOUNT) VALUES (@last_header_id, 8, '貸方', 820000);

-- 2024年6月の売上データ
INSERT INTO JOURNAL_HEADERS (ENTRY_DATE, DESCRIPTION) VALUES ('2024-06-30', '2024年6月売上');
SET @last_header_id = LAST_INSERT_ID();
INSERT INTO JOURNAL_ENTRIES (HEADER_ID, ACCOUNT_ID, TYPE, AMOUNT) VALUES (@last_header_id, 1, '借方', 800000);
INSERT INTO JOURNAL_ENTRIES (HEADER_ID, ACCOUNT_ID, TYPE, AMOUNT) VALUES (@last_header_id, 8, '貸方', 800000);

-- 2024年7月の売上データ
INSERT INTO JOURNAL_HEADERS (ENTRY_DATE, DESCRIPTION) VALUES ('2024-07-31', '2024年7月売上');
SET @last_header_id = LAST_INSERT_ID();
INSERT INTO JOURNAL_ENTRIES (HEADER_ID, ACCOUNT_ID, TYPE, AMOUNT) VALUES (@last_header_id, 1, '借方', 980000);
INSERT INTO JOURNAL_ENTRIES (HEADER_ID, ACCOUNT_ID, TYPE, AMOUNT) VALUES (@last_header_id, 8, '貸方', 980000);

-- 2024年8月の売上データ
INSERT INTO JOURNAL_HEADERS (ENTRY_DATE, DESCRIPTION) VALUES ('2024-08-31', '2024年8月売上');
SET @last_header_id = LAST_INSERT_ID();
INSERT INTO JOURNAL_ENTRIES (HEADER_ID, ACCOUNT_ID, TYPE, AMOUNT) VALUES (@last_header_id, 1, '借方', 1150000);
INSERT INTO JOURNAL_ENTRIES (HEADER_ID, ACCOUNT_ID, TYPE, AMOUNT) VALUES (@last_header_id, 8, '貸方', 1150000);

-- 2024年9月の売上データ
INSERT INTO JOURNAL_HEADERS (ENTRY_DATE, DESCRIPTION) VALUES ('2024-09-30', '2024年9月売上');
SET @last_header_id = LAST_INSERT_ID();
INSERT INTO JOURNAL_ENTRIES (HEADER_ID, ACCOUNT_ID, TYPE, AMOUNT) VALUES (@last_header_id, 1, '借方', 880000);
INSERT INTO JOURNAL_ENTRIES (HEADER_ID, ACCOUNT_ID, TYPE, AMOUNT) VALUES (@last_header_id, 8, '貸方', 880000);

-- 2024年10月の売上データ
INSERT INTO JOURNAL_HEADERS (ENTRY_DATE, DESCRIPTION) VALUES ('2024-10-31', '2024年10月売上');
SET @last_header_id = LAST_INSERT_ID();
INSERT INTO JOURNAL_ENTRIES (HEADER_ID, ACCOUNT_ID, TYPE, AMOUNT) VALUES (@last_header_id, 1, '借方', 950000);
INSERT INTO JOURNAL_ENTRIES (HEADER_ID, ACCOUNT_ID, TYPE, AMOUNT) VALUES (@last_header_id, 8, '貸方', 950000);

-- 2024年11月の売上データ
INSERT INTO JOURNAL_HEADERS (ENTRY_DATE, DESCRIPTION) VALUES ('2024-11-30', '2024年11月売上');
SET @last_header_id = LAST_INSERT_ID();
INSERT INTO JOURNAL_ENTRIES (HEADER_ID, ACCOUNT_ID, TYPE, AMOUNT) VALUES (@last_header_id, 1, '借方', 1080000);
INSERT INTO JOURNAL_ENTRIES (HEADER_ID, ACCOUNT_ID, TYPE, AMOUNT) VALUES (@last_header_id, 8, '貸方', 1080000);

-- 2024年12月の売上データ
INSERT INTO JOURNAL_HEADERS (ENTRY_DATE, DESCRIPTION) VALUES ('2024-12-31', '2024年12月売上');
SET @last_header_id = LAST_INSERT_ID();
INSERT INTO JOURNAL_ENTRIES (HEADER_ID, ACCOUNT_ID, TYPE, AMOUNT) VALUES (@last_header_id, 1, '借方', 1350000);
INSERT INTO JOURNAL_ENTRIES (HEADER_ID, ACCOUNT_ID, TYPE, AMOUNT) VALUES (@last_header_id, 8, '貸方', 1350000);
-- 2025年1月の売上データ
INSERT INTO JOURNAL_HEADERS (ENTRY_DATE, DESCRIPTION) VALUES ('2025-01-31', '2025年1月売上');
SET @last_header_id = LAST_INSERT_ID();
INSERT INTO JOURNAL_ENTRIES (HEADER_ID, ACCOUNT_ID, TYPE, AMOUNT) VALUES (@last_header_id, 8, '借方', 1150000);
INSERT INTO JOURNAL_ENTRIES (HEADER_ID, ACCOUNT_ID, TYPE, AMOUNT) VALUES (@last_header_id, 1, '貸方', 1150000);

-- 2025年2月の売上データ
INSERT INTO JOURNAL_HEADERS (ENTRY_DATE, DESCRIPTION) VALUES ('2025-02-28', '2025年2月売上');
SET @last_header_id = LAST_INSERT_ID();
INSERT INTO JOURNAL_ENTRIES (HEADER_ID, ACCOUNT_ID, TYPE, AMOUNT) VALUES (@last_header_id, 8, '借方', 1220000);
INSERT INTO JOURNAL_ENTRIES (HEADER_ID, ACCOUNT_ID, TYPE, AMOUNT) VALUES (@last_header_id, 1, '貸方', 1220000);

-- 2025年3月の売上データ
INSERT INTO JOURNAL_HEADERS (ENTRY_DATE, DESCRIPTION) VALUES ('2025-03-31', '2025年3月売上');
SET @last_header_id = LAST_INSERT_ID();
INSERT INTO JOURNAL_ENTRIES (HEADER_ID, ACCOUNT_ID, TYPE, AMOUNT) VALUES (@last_header_id, 8, '借方', 1280000);
INSERT INTO JOURNAL_ENTRIES (HEADER_ID, ACCOUNT_ID, TYPE, AMOUNT) VALUES (@last_header_id, 1, '貸方', 1280000);

-- 2025年4月の売上データ
INSERT INTO JOURNAL_HEADERS (ENTRY_DATE, DESCRIPTION) VALUES ('2025-04-30', '2025年4月売上');
SET @last_header_id = LAST_INSERT_ID();
INSERT INTO JOURNAL_ENTRIES (HEADER_ID, ACCOUNT_ID, TYPE, AMOUNT) VALUES (@last_header_id, 8, '借方', 1350000);
INSERT INTO JOURNAL_ENTRIES (HEADER_ID, ACCOUNT_ID, TYPE, AMOUNT) VALUES (@last_header_id, 1, '貸方', 1350000);

-- 2025年5月の売上データ
INSERT INTO JOURNAL_HEADERS (ENTRY_DATE, DESCRIPTION) VALUES ('2025-05-31', '2025年5月売上');
SET @last_header_id = LAST_INSERT_ID();
INSERT INTO JOURNAL_ENTRIES (HEADER_ID, ACCOUNT_ID, TYPE, AMOUNT) VALUES (@last_header_id, 8, '借方', 1400000);
INSERT INTO JOURNAL_ENTRIES (HEADER_ID, ACCOUNT_ID, TYPE, AMOUNT) VALUES (@last_header_id, 1, '貸方', 1400000);

-- 2025年6月の売上データ
INSERT INTO JOURNAL_HEADERS (ENTRY_DATE, DESCRIPTION) VALUES ('2025-06-30', '2025年6月売上');
SET @last_header_id = LAST_INSERT_ID();
INSERT INTO JOURNAL_ENTRIES (HEADER_ID, ACCOUNT_ID, TYPE, AMOUNT) VALUES (@last_header_id, 8, '借方', 1450000);
INSERT INTO JOURNAL_ENTRIES (HEADER_ID, ACCOUNT_ID, TYPE, AMOUNT) VALUES (@last_header_id, 1, '貸方', 1450000);

-- 2025年7月の売上データ
INSERT INTO JOURNAL_HEADERS (ENTRY_DATE, DESCRIPTION) VALUES ('2025-07-31', '2025年7月売上');
SET @last_header_id = LAST_INSERT_ID();
INSERT INTO JOURNAL_ENTRIES (HEADER_ID, ACCOUNT_ID, TYPE, AMOUNT) VALUES (@last_header_id, 8, '借方', 1500000);
INSERT INTO JOURNAL_ENTRIES (HEADER_ID, ACCOUNT_ID, TYPE, AMOUNT) VALUES (@last_header_id, 1, '貸方', 1500000);
