-- テーブル関係

-- 勘定科目テーブル
CREATE TABLE ACCOUNTS (
  ID INTEGER AUTO_INCREMENT PRIMARY KEY,
  -- 勘定科目名
  NAME VARCHAR(100) NOT NULL,
  -- 種類（資産、負債など）
  TYPE ENUM('資産', '負債', '純資産', '収益', '費用') NOT NULL, 
  -- 勘定科目コード
  CODE VARCHAR(100) UNIQUE
);
-- 仕訳ヘッダーテーブル（1件の取引全体を表す）
CREATE TABLE JOURNAL_HEADERS (
  -- 仕訳ヘッダーID
  ID INTEGER AUTO_INCREMENT PRIMARY KEY,
  -- 取引日付
  ENTRY_DATE DATE NOT NULL,
  -- 摘要
  DESCRIPTION TEXT,
  -- 登録日時
  CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
-- 仕訳明細テーブル
CREATE TABLE JOURNAL_ENTRIES (
    -- 仕訳明細ID (自動採番)
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,

    -- 仕訳ヘッダーの外部キー
    HEADER_ID INTEGER NOT NULL,

    -- 勘定科目
    ACCOUNT_ID INTEGER NOT NULL,

    -- 金額
    AMOUNT INTEGER NOT NULL,

    -- 借方 or 貸方
    TYPE ENUM('借方', '貸方') NOT NULL,

    -- 外部キー制約
    FOREIGN KEY (HEADER_ID) REFERENCES JOURNAL_HEADERS(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS(ID) ON DELETE RESTRICT ON UPDATE CASCADE
);


-- USERSテーブルの作成
-- #CREATE TABLE USERS (
--   u_id INT AUTO_INCREMENT PRIMARY KEY,
--   u_name VARCHAR(100) NOT NULL,
--   u_pass VARCHAR(100) NOT NULL,
--   u_dname VARCHAR(100) NOT NULL
-- );
