--年・月での集計用___〇年〇月〇円
CREATE TABLE SALES_REPORTS(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    SALES_YEAR INT NOT NULL,
    SALES_MONTH INT NOT NULL,
    SALES_AMOUNT INT NOT NULL, 
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY (SALES_YEAR, SALES_MONTH)
);


--売上のデータ一件
CREATE TABLE SALES_ENTRIES(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    SALE_DATE DATE NOT NULL,
    --大ちゃんの取引先企業ID
    --そうてぃー取引担当者ID
    --ちゃん堂の取引商品詳細？をまとめてるテーブルの主キー
    SALE_AMOUNT INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

